package models

const (
	//Ceramic ...
	Ceramic = "ceramic"
	//Silicate ...
	Silicate = "silicate"
	//GasBlock ...
	GasBlock = "gas block"
	//NoMoneyForBricks ...
	NoMoneyForBricks = "no money for bricks"
	//CeramicCost ...
	CeramicCost = 1800.0
	//SilicateCost ...
	SilicateCost = 1500.0
	//GasBlockCost ...
	GasBlockCost = 1100.0
)
