package models

const (
	//Masons ...
	Masons = "masons"
	//Handymen ...
	Handymen = "handymen"
	//NoMoney ...
	NoMoney = "not enough money for builders"
	//MasonsCost ...
	MasonsCost = 10000.0
	//HandymenCost ...
	HandymenCost = 5000.0
)
