package models

const (
	//Ceramic ...
	Ceramic = "ceramic"
	//Silicate ...
	Silicate = "silicate"
	//GasBlock ...
	GasBlock = "gas block"
	//NoMoney ...
	NoMoney = "no money for bricks"
	//CeramicCost ...
	CeramicCost = 1800.0
	//SilicateCost ...
	SilicateCost = 1500.0
	//GasBlockCost ...
	GasBlockCost = 1100.0
)

//BrickType ...
type BrickType string

//Cost ...
type Cost float64
